# Generated by Django 6.0.2 on 2026-04-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_gradingtimeframe_courseclass_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
